<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "jobs"
 *
 * Auto generated by Extension Builder 2019-10-21
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Jobs',
    'description' => 'This extension enables you to manage job postings, the application form and incoming applications.',
    'category' => 'plugin',
    'author' => 'Stefanie Döll, Benjamin Jasper',
	'author_company' => 'it.x informationssysteme gmbh',
    'author_email' => '',
    'state' => 'beta',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 1,
    'version' => '0.0.9',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
