routeEnhancers:
    JobapplicationsListView:
        type: Extbase
        namespace: tx_jobapplications_frontend
        routes:
            -   routePath: '/'
                _controller: 'Posting::list'
            -   routePath: '/page-{page}'
                _controller: 'Posting::list'
                _arguments:
                    page: 'page'
                requirements:
                    page: \d+
        defaultController: 'Posting::list'
        aspects:
            page:
                type: StaticRangeMapper
                start: '1'
                end: '25'
    JobapplicationsDetailView:
        type: Extbase
        namespace: 'tx_jobapplications_detailview'
        routes:
            -   routePath: '/position/{slug}'
                _controller: 'Posting::show'
                _arguments:
                    slug: posting
        defaultController: 'Posting::list'
        defaults:
            page: ''
        aspects:
            slug:
                type: PersistedAliasMapper
                tableName: tx_jobapplications_domain_model_posting
                routeFieldName: slug
    JobapplicationsApplicationForm:
        type: Extbase
        namespace: 'tx_jobapplications_applicationform'
        routes:
            -   routePath: '/{slug}'
                _controller: 'Application::new'
                _arguments:
                    slug: posting
        defaultController: 'Application::new'
        defaults:
            page: ''
        aspects:
            slug:
                type: PersistedAliasMapper
                tableName: tx_jobapplications_domain_model_posting
                routeFieldName: slug